### PR TITLE
Erik Group Sprint Progress: AI, Managers, 3D Assets and map adaptation

### PR DESCRIPTION
**Pull request by Valerifesta**
**Additions**

Erik AI, Managers(Animations & behavioural), Erik models and animations, placeholder playermovement (can be removed once real player movement has been added).

Specifications: Setting up the AI and general info-
Erik has a functioning AI that is already (somewhat) pre-adapted to an existing version of the map. In order for the AI to work, 4 things need to exist in the scene. (Note that all current prefabs related to the AI is found in a prefab folder under Valerie's name because of organizing reasons, this can be changed within the main repos since it is pretty messy.):
1. The A* prefab 
2. The Erik prefab
3. The Animation manager
4. The Erik Manager (the Erik game object has to be manually assigned to the ErikObj variable.)
5. A player object with the "Player" tag.

A thing to take note of is that an observed AI bug is shown to appear at times which results in Erik phasing up and standing on roofs. This is due to a complication with how colliders elevated from the floor interacts with the pathfinding scanning. Has a possible easy fix, unsure if it will be implemented before the sprint. Overall, progress is pretty okay for a play test. 

Any questions regarding the following Erik topics can be asked about from the following people:
Sound Assets - Neo & Adrian
AI Behaviour- Valeire & Isak
3D Assets & Animation - David SC & Derrick

### CODE REVIEW

**Review by izzyn — CHANGES_REQUESTED** [review]
Stoppa in ändringarna för gruppen i en dedikerad mapp, annars ser allt bra ut :)

**Review by Blixtdraken — DISMISSED** [review]
👍

**Comment by Valerifesta** [comment]
Me and pontus fixed errors (YIPÅPIE)

**Comment by Valerifesta** [comment]
Erik_Happy-face_Texture

**Review by izzyn — APPROVED** [review]
Yippie allt fixat

**Pull request merged**
